//COUNTRIES
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const FILTER_COUNTRIES = 'FILTER_COUNTRIES'
export const GET_COUNTRY_BY_ID = 'GET_COUNTRY_BY_ID';
export const CLEAN_COUNTRY_ID = 'CLEAN_COUNTRY_ID';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE'

//ACTIVITIES

export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES';
export const CREATE_NEW_ACTIVITY = 'CREATE_NEW_ACTIVITY';
export const LOADING_NEW_ACTIVITY = 'LOADING_NEW_ACTIVITY';
export const CLEAN = 'CLEAN';