//COUNTRIES
export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const GET_ALL_COUNTRIES_BY_NAME = 'GET_ALL_COUNTRIES_BY_NAME';
export const GET_ALL_COUNTRIES_BY_CONTINENT = 'GET_ALL_COUNTRIES_BY_CONTINENT';
export const GET_ALL_COUNTRIES_BY_ALPHABETICALLY = 'GET_ALL_COUNTRIES_BY_ALPHABETICALLY';
export const GET_ALL_COUNTRIES_BY_POPULATION = 'GET_ALL_COUNTRIES_BY_POPULATION';
export const GET_ALL_COUNTRIES_BY_ACTIVITIES = 'GETT_ALL_COUNTRIES_BY_ACTIVITIES';
export const GET_COUNTRY_BY_ID = 'GET_COUNTRY_BY_ID';
export const CLEAN_COUNTRY_ID = 'CLEAN_COUNTRY_ID';

//ACTIVITIES

export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES';
export const CREATE_NEW_ACTIVITY = 'CREATE_NEW_ACTIVITY';
export const LOADING_NEW_ACTIVITY = 'LOADING_NEW_ACTIVITY';
export const CLEAN = 'CLEAN';